theme: jekyll-theme-dinky

title: Maratona SBC
description: Problemas da Maratona resolvidos em Potigol
google_analytics: UA-66397531-1
show_downloads: true
markdown: kramdown
highlighter: rouge
  
plugins:
  - jemoji
